### ISSUE TITLE
`npm run prepublish error` when running `npm run lerna`

### ISSUE THREAD

**Issue by john-co** [metal/metal.js#412]
1. Run `npm install -g lerna@2.2.0`
2. Run `npm run lerna`
Assert console log errors:

```
/metal.js   master v2.16.8 ● ?  npm run lerna                                                                                                                         2912  16:47:28

> @ lerna /home/john-co/Liferay/frontend-infra-repos/metal.js
> lerna bootstrap -- --no-optional && npm install --no-optional

lerna info version 2.11.0
lerna info Bootstrapping 13 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna WARN EREPLACE_EXIST metal is already installed for metal-web-component. Replacing with symlink...
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna ERR! execute Error occured with 'metal-soy-bundle' while running 'npm run prepublish'
lerna ERR! npm run prepublish [metal-soy-bundle] Output from stdout:

> metal-soy-bundle@2.16.8 prepublish /home/john-co/Liferay/frontend-infra-repos/metal.js/packages/metal-soy-bundle
> npm run build && npm run compile


> metal-soy-bundle@2.16.8 build /home/john-co/Liferay/frontend-infra-repos/metal.js/packages/metal-soy-bundle
> gulp


lerna ERR! npm run prepublish [metal-soy-bundle] Output from stderr:
gulp[28383]: ../src/node_contextify.cc:635:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: 0x8fa0c0 node::Abort() [gulp]
 2: 0x8fa195  [gulp]
 3: 0x92e5be node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
 4: 0xb8d2db  [gulp]
 5: 0xb8f272 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
 6: 0x4c69ecdbe1d 
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! metal-soy-bundle@2.16.8 build: `gulp`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the metal-soy-bundle@2.16.8 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/john-co/.npm/_logs/2020-01-07T00_47_38_600Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! metal-soy-bundle@2.16.8 prepublish: `npm run build && npm run compile`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the metal-soy-bundle@2.16.8 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/john-co/.npm/_logs/2020-01-07T00_47_38_613Z-debug.log

lerna ERR! execute Error occured with 'metal-soy-bundle' while running 'npm run prepublish'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
{ Error: Command failed: npm run prepublishplete Waiting for 1 child process to exit. CTRL-C to exit immediately.
gulp[28383]: ../src/node_contextify.cc:635:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: 0x8fa0c0 node::Abort() [gulp]
 2: 0x8fa195  [gulp]
 3: 0x92e5be node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
 4: 0xb8d2db  [gulp]
 5: 0xb8f272 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
 6: 0x4c69ecdbe1d 
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! metal-soy-bundle@2.16.8 build: `gulp`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the metal-soy-bundle@2.16.8 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/john-co/.npm/_logs/2020-01-07T00_47_38_600Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! metal-soy-bundle@2.16.8 prepublish: `npm run build && npm run compile`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the metal-soy-bundle@2.16.8 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/john-co/.npm/_logs/2020-01-07T00_47_38_613Z-debug.log

> metal-soy-bundle@2.16.8 prepublish /home/john-co/Liferay/frontend-infra-repos/metal.js/packages/metal-soy-bundle
> npm run build && npm run compile


> metal-soy-bundle@2.16.8 build /home/john-co/Liferay/frontend-infra-repos/metal.js/packages/metal-soy-bundle
> gulp


    at Promise.all.then.arr (/home/john-co/Liferay/frontend-infra-repos/metal.js/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 134,
  killed: false,
  stdout:
   '\n> metal-soy-bundle@2.16.8 prepublish /home/john-co/Liferay/frontend-infra-repos/metal.js/packages/metal-soy-bundle\n> npm run build && npm run compile\n\n\n> metal-soy-bundle@2.16.8 build /home/john-co/Liferay/frontend-infra-repos/metal.js/packages/metal-soy-bundle\n> gulp\n\n',
  stderr:
   'gulp[28383]: ../src/node_contextify.cc:635:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()\' failed.\n 1: 0x8fa0c0 node::Abort() [gulp]\n 2: 0x8fa195  [gulp]\n 3: 0x92e5be node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]\n 4: 0xb8d2db  [gulp]\n 5: 0xb8f272 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]\n 6: 0x4c69ecdbe1d \nAborted (core dumped)\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 134\nnpm ERR! metal-soy-bundle@2.16.8 build: `gulp`\nnpm ERR! Exit status 134\nnpm ERR! \nnpm ERR! Failed at the metal-soy-bundle@2.16.8 build script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/john-co/.npm/_logs/2020-01-07T00_47_38_600Z-debug.log\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 134\nnpm ERR! metal-soy-bundle@2.16.8 prepublish: `npm run build && npm run compile`\nnpm ERR! Exit status 134\nnpm ERR! \nnpm ERR! Failed at the metal-soy-bundle@2.16.8 prepublish script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/john-co/.npm/_logs/2020-01-07T00_47_38_613Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm run prepublish',
  timedOut: false,
  pkg:
   Package {
     _package:
      { name: 'metal-soy-bundle',
        version: '2.16.8',
        description:
         'A bundle containing all the closure dependencies required by soy files compiled to incremental-dom',
        license: 'MIT',
        repository:
         'https://github.com/metal/metal.js/tree/master/packages/metal-soy-bundle',
        author: [Object],
        engines: [Object],
        'jsnext:main': 'build/bundle.js',
        main: 'lib/bundle.js',
        files: [Array],
        scripts: [Object],
        devDependencies: [Object],
        dependencies: [Object] },
     _location:
      '/home/john-co/Liferay/frontend-infra-repos/metal.js/packages/metal-soy-bundle' },
  exitCode: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ lerna: `lerna bootstrap -- --no-optional && npm install --no-optional`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ lerna script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/john-co/.npm/_logs/2020-01-07T00_47_38_850Z-debug.log
```

**Comment by jbalsas** [comment]
Hey @john-co, this is likely a problem with your node version. Which version are you currently using? Can you try with and older one?

**Comment by john-co** [comment]
Hi @jbalsas 

**Reproduced on** node 12.11.1 and 10.16.3

**Not Reproducible on** node 8.11.3 and 8.17.0
